# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jijeong <jijeong@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/05/12 22:45:09 by jijeong           #+#    #+#              #
#    Updated: 2026/05/12 22:45:11 by jijeong          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./mariadb_data:/var/lib/mysql
        env_file:
            - .env
